[2024-10-13 10:48:40,211] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-10-13 10:48:40,211] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-10-13 10:48:44,720] 97 werkzeug - INFO - 127.0.0.1 - - [13/Oct/2024 10:48:44] "GET /prediction HTTP/1.1" 200 -
[2024-10-13 10:48:55,651] 838 app - ERROR - Exception on /prediction [POST]
Traceback (most recent call last):
  File "E:\Data_Science _master\ML\Diamonda_prediction\env\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Data_Science _master\ML\Diamonda_prediction\env\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Data_Science _master\ML\Diamonda_prediction\env\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Data_Science _master\ML\Diamonda_prediction\env\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 30, in predict_datapoint
    table=float(request.form.get("table")),
TypeError: float() argument must be a string or a number, not 'NoneType'
[2024-10-13 10:48:55,654] 97 werkzeug - INFO - 127.0.0.1 - - [13/Oct/2024 10:48:55] "[35m[1mPOST /prediction HTTP/1.1[0m" 500 -
